"""ALB Lambda target: admin-only listing of, and downloads from, the uploads bucket.

Sits behind the frontend's ALB on `/api/admin/*`, reusing the same Cognito
authentication action as the rest of the site (wired up in `app.py`).

Routes (GET only):
    /api/admin/uploads?limit=50&cursor=...
        -> {"items": [...], "nextCursor": "..." | null}
    /api/admin/download?key=uploads/2026/01/01/<uuid>/report.pdf
        -> {"url": "<presigned GET, valid for seconds>"}

Access control
--------------
Only members of the platform `gds-idea` Cognito group may use this API
(`User.is_gds_idea`). Identity and groups come from `cognito-auth`'s
`LambdaAuth`, with no `Authoriser` - this is a deliberately team-only
feature, so there is no per-app allow/admin list to resolve.

Every failure to establish identity fails CLOSED (401), and an identified
non-member gets 403. Unlike the presign Lambda, which treats attribution as
best-effort, nothing here may fall back to "anonymous".

SECURITY NOTE: the group check is only as trustworthy as token verification
in `cognito-auth`, which currently does not pin the expected issuer or ALB
signer, and as the Lambda's resource policy, which must only let *our*
target group invoke it (see `backend_stack.py`). Do not expose this function
via a Function URL or any other invoke path.

Listing
-------
Uploader identity lives only in S3 object metadata, so this lists keys under
`uploads/`, orders them newest-first by LastModified, and calls `head_object`
only for the requested page. Pagination uses an opaque cursor (the last
(LastModified, key) returned) so it stays stable as new uploads arrive.
"""

from __future__ import annotations

import base64
import json
import os
import re
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from http import HTTPStatus
from urllib.parse import unquote

import boto3
from aws_lambda_powertools import Logger
from botocore.config import Config
from botocore.exceptions import ClientError
from cognito_auth.lambda_auth import LambdaAuth

logger = Logger(service="drop-admin-uploads")

_AWS_REGION = os.environ.get("AWS_REGION", "eu-west-2")

# Same client settings (and reasons) as the presign Lambda: regional endpoint
# + virtual addressing + explicit SigV4, so presigned URLs work directly from
# a browser in a non-us-east-1 region.
s3_client = boto3.client(
    "s3",
    region_name=_AWS_REGION,
    config=Config(signature_version="s3v4", s3={"addressing_style": "virtual"}),
)

BUCKET_NAME = os.environ["UPLOADS_BUCKET_NAME"]

# Kept short: the URL is a bearer credential and ends up in browser history.
DOWNLOAD_URL_EXPIRY_SECONDS = int(os.environ.get("DOWNLOAD_URL_EXPIRY_SECONDS", "60"))

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200

# Listing has to see every key to order newest-first (S3 lists oldest-first).
# Fail loudly rather than silently omit the newest uploads if that ever gets
# too big - at that point an index (e.g. DynamoDB) is the right answer.
MAX_LISTED_KEYS = 100_000

_HEAD_WORKERS = 10

# authoriser=None: see module docstring. The ALB has already authenticated
# the caller; this only extracts a *verified* identity and its groups.
_auth = LambdaAuth(authoriser=None, region=_AWS_REGION)

# Keys are only ever generated by presign's `_build_key`, so validate against
# that exact shape rather than trying to blacklist bad input.
_KEY_RE = re.compile(
    r"^uploads/\d{4}/\d{2}/\d{2}/"
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/"
    r"[A-Za-z0-9._-]{1,255}$"
)

_UPLOADS_PREFIX = "uploads/"


class _ListingTooLargeError(Exception):
    pass


def handler(event, context):
    """Handle an ALB request. Never raises: unexpected errors become a 500."""
    try:
        return _handle(event)
    except Exception:
        logger.exception("unhandled error in admin uploads handler")
        return _response(500, {"error": "Internal error"})


def _handle(event: dict) -> dict:
    user = _authenticate(event)
    if isinstance(user, dict):
        return user  # an error response

    if event.get("httpMethod", "GET") != "GET":
        return _response(405, {"error": "Method not allowed"})

    path = (event.get("path") or "").rstrip("/")
    if path.endswith("/api/admin/uploads"):
        return _handle_list(event)
    if path.endswith("/api/admin/download"):
        return _handle_download(event, user)
    return _response(404, {"error": "Not found"})


def _authenticate(event: dict):
    """Return the verified gds-idea `User`, or an error response dict."""
    try:
        user = _auth.get_auth_user(event)
    except Exception as exc:  # noqa: BLE001 - any failure must fail closed
        logger.warning(f"admin request without verifiable identity: {exc!r}")
        return _response(401, {"error": "Authentication required"})

    if not user.is_gds_idea:
        logger.warning(
            "admin request denied: not in gds-idea group",
            denied_email=user.email,
            denied_sub=user.sub,
        )
        return _response(403, {"error": "Forbidden"})

    return user


# --- Listing ---------------------------------------------------------------


def _handle_list(event: dict) -> dict:
    params = event.get("queryStringParameters") or {}

    try:
        limit = _parse_limit(params.get("limit"))
        cursor = _decode_cursor(_query_param(params, "cursor"))
    except ValueError as exc:
        return _response(400, {"error": str(exc)})

    try:
        objects = _list_all_objects()
    except _ListingTooLargeError:
        logger.error("uploads listing exceeds MAX_LISTED_KEYS", max=MAX_LISTED_KEYS)
        return _response(500, {"error": "Too many uploads to list"})

    # Newest first; key as a tiebreaker keeps the ordering total so the
    # cursor is exact.
    objects.sort(key=lambda o: (o["LastModified"], o["Key"]), reverse=True)

    if cursor is not None:
        objects = [o for o in objects if (o["LastModified"], o["Key"]) < cursor]

    page = objects[:limit]
    with ThreadPoolExecutor(max_workers=_HEAD_WORKERS) as pool:
        items = list(pool.map(_describe_object, page))

    next_cursor = None
    if len(objects) > limit and page:
        last = page[-1]
        next_cursor = _encode_cursor(last["LastModified"], last["Key"])

    return _response(200, {"items": items, "nextCursor": next_cursor})


def _list_all_objects() -> list[dict]:
    objects: list[dict] = []
    paginator = s3_client.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=BUCKET_NAME, Prefix=_UPLOADS_PREFIX):
        for obj in page.get("Contents", []):
            if obj["Key"].endswith("/"):
                continue  # folder placeholder, not an upload
            objects.append(obj)
            if len(objects) > MAX_LISTED_KEYS:
                raise _ListingTooLargeError
    return objects


def _describe_object(obj: dict) -> dict:
    """Build the API item for one object, enriched from head_object metadata."""
    key = obj["Key"]
    item = {
        "key": key,
        "filename": key.rsplit("/", 1)[-1],
        "size": obj.get("Size"),
        "uploadedAt": obj["LastModified"].isoformat(),
        "uploadedByEmail": None,
        "uploadedByName": None,
        "contentType": None,
    }

    try:
        head = s3_client.head_object(Bucket=BUCKET_NAME, Key=key)
    except ClientError as exc:
        # e.g. deleted between list and head. Still show what the listing
        # told us rather than failing the whole page.
        logger.warning(f"head_object failed for {key}: {exc}")
        return item

    metadata = head.get("Metadata", {})
    item["uploadedAt"] = metadata.get("uploaded-at") or item["uploadedAt"]
    item["uploadedByEmail"] = metadata.get("uploaded-by-email")
    item["uploadedByName"] = metadata.get("uploaded-by-name")
    item["contentType"] = head.get("ContentType")
    return item


def _query_param(params: dict, name: str) -> str:
    """Read a query parameter, URL-decoded.

    ALB hands Lambda targets query strings exactly as received (still
    percent-encoded), so `key=uploads%2F2026...` must be decoded here.
    """
    return unquote(params.get(name) or "")


def _parse_limit(raw: str | None) -> int:
    if raw is None or raw == "":
        return DEFAULT_PAGE_SIZE
    try:
        limit = int(raw)
    except ValueError as exc:
        raise ValueError("limit must be an integer") from exc
    if not 1 <= limit <= MAX_PAGE_SIZE:
        raise ValueError(f"limit must be between 1 and {MAX_PAGE_SIZE}")
    return limit


def _encode_cursor(last_modified: datetime, key: str) -> str:
    raw = json.dumps({"t": last_modified.isoformat(), "k": key})
    return base64.urlsafe_b64encode(raw.encode()).decode()


def _decode_cursor(raw: str | None) -> tuple[datetime, str] | None:
    if not raw:
        return None
    try:
        data = json.loads(base64.urlsafe_b64decode(raw.encode()))
        return datetime.fromisoformat(data["t"]), str(data["k"])
    except (ValueError, KeyError, TypeError) as exc:
        raise ValueError("invalid cursor") from exc


# --- Download --------------------------------------------------------------


def _handle_download(event: dict, user) -> dict:
    params = event.get("queryStringParameters") or {}
    key = _query_param(params, "key")

    if not _KEY_RE.match(key):
        return _response(400, {"error": "Invalid key"})

    try:
        s3_client.head_object(Bucket=BUCKET_NAME, Key=key)
    except ClientError as exc:
        if exc.response.get("Error", {}).get("Code") in (
            "404",
            "NoSuchKey",
            "NotFound",
        ):
            return _response(404, {"error": "Not found"})
        raise

    filename = key.rsplit("/", 1)[
        -1
    ]  # already restricted to safe characters by _KEY_RE
    url = s3_client.generate_presigned_url(
        "get_object",
        Params={
            "Bucket": BUCKET_NAME,
            "Key": key,
            # The stored ContentType is whatever the uploader claimed, so
            # never let the browser render it inline.
            "ResponseContentDisposition": f'attachment; filename="{filename}"',
            "ResponseContentType": "application/octet-stream",
        },
        ExpiresIn=DOWNLOAD_URL_EXPIRY_SECONDS,
    )

    logger.info(
        "admin_download",
        key=key,
        admin_email=user.email,
        admin_sub=user.sub,
    )
    return _response(200, {"url": url})


# --- Response --------------------------------------------------------------


def _response(status_code: int, body_dict: dict) -> dict:
    """Build an ALB-compatible Lambda target response.

    `no-store` matters: listings contain uploader PII and download responses
    contain bearer URLs - neither may be cached by the browser or any proxy.
    """
    phrase = HTTPStatus(status_code).phrase
    return {
        "statusCode": status_code,
        "statusDescription": f"{status_code} {phrase}",
        "headers": {
            "Content-Type": "application/json",
            "Cache-Control": "no-store",
            "X-Content-Type-Options": "nosniff",
        },
        "body": json.dumps(body_dict),
        "isBase64Encoded": False,
    }
